### ISSUE TITLE
Usage with external UVC webcam

### ISSUE THREAD

**Issue by paul-hristea** [Dynamsoft/capture-vision-flutter-samples#9]
Hello,

Is there a way to use this plugin with an external camera connected through USB to an Android 7.1 tablet?

I see in the Dynamsoft Android SDK that there are methods for selecting a camera by ID rather than just Front/Back -facing. Is there any way to use this from Flutter at this time?

Thank you

**Comment by Dynamsoft-Henry** [comment]
Hi @paul-hristea 

Our camera APIs are designed to support `mobile camera` only. Since your camera is an `external camera`, I think it is not in the ID list.

To use your external camera with this library, you can:

1. Develop your own code to support your camera and get image from the camera.
2. Use our decode method to decode the image you get.
